
images:
  - name: codefresh/cf-base
    base: ubuntu:14.04
    services:
      apt:
        packages: git ssh sshpass
      nodejs:
      sass:

#  - name: codefresh/cf-base-mongodb
#    base: codefresh/cf-base
#    services:
#      local-mongodb:

